🥚 manual de ejecución
IslasGECI/juego_10_nativos_dijeron pull request #11
Opened 2021-01-27 19:52 UTC by xwalls

Abro este PR para trabajar sobre el manual de ejecución de la aplicación

2021-01-28 23:25 UTC, xwalls commented
Se hizo un archivo que facilita la ejecución de la aplicación mediante un script de batch para windows.
el script ejecuta los siguientes comandos:
`start "" http://localhost:8080/`
`java -jar 10-nativos-dijeron.jar`

2021-02-18 18:41 UTC, nepito requested changes
Esto fue el avance de la semana pasada. 

Las instrucciones para instalar las dependencias: descargar, instalar dependencias y ejecutar.

2021-02-18 18:41 UTC, nepito commented on MANUAL.md
> +_Que cosas necesitas tener antes de poder ejecutar la aplicacions:_
Error de dedo, te faltó una tilde **Qué** y otra en **aplicación**:
```suggestion
_Qué cosas necesitas tener antes de poder ejecutar la aplicación:_
```

2021-02-25 00:00 UTC, xwalls commented on MANUAL.md
> +_Que cosas necesitas tener antes de poder ejecutar la aplicacions:_
gracias @nepito 
acepto tu sugerencia!

2021-04-09 21:01 UTC, MaritzaB requested changes
@xwalls te dejo una primera revisión. Es muy somera, pero le seguiré dando la próxima semana 🙌🏽 ¿va?

2021-04-09 21:01 UTC, MaritzaB commented on MANUAL.md
> +# Manual de Instalacion y Ejecucion
```suggestion
# Manual de instalacion y ejecución
```

2021-04-09 21:01 UTC, MaritzaB commented on MANUAL.md
> +Debemos asegurarnos de seguir los pasos para garantizar su funcionalidad._
```suggestion
_Este es el manual de instalación del juego _10 nativos dijeron_. Aquí veremos los pre-requisitos de sistema para poder instalar y ejecutar esta aplicacion, así como las instrucciones para hacerlo._
```

2021-04-09 21:01 UTC, MaritzaB commented on MANUAL.md
> +
Como que siento que esta sección no aporta mucho, ya que arriba mencionamos lo que vamos a ver en el manual. Así que yo creo que la podemos eliminar.
```suggestion

```

2021-04-09 21:01 UTC, MaritzaB commented on MANUAL.md
> +### Pre-requisitos 📋
```suggestion
### Pre-requisitos del sistema 📋
```

2021-04-09 21:01 UTC, MaritzaB commented on MANUAL.md
> +- Tener un sistema operativos (windows, ubuntu, macOs)
Qué opinas de lo siguiente:
```suggestion
- Tener un sistema operativo windows, ubuntu ó macOS
```

2021-04-09 21:01 UTC, MaritzaB commented on MANUAL.md
> +- ejecutar en windwos.bat
```suggestion
- ejecutar en windows.bat
```

2021-04-09 21:01 UTC, MaritzaB commented on MANUAL.md
> +Para ejecutar la aplicacion debemos hacer doble click sobre el archivo `ejecutar_en_windwos.bat`
```suggestion
Para ejecutar la aplicacion debemos hacer doble click sobre el archivo `ejecutar_en_windows.bat` 
```

2021-04-13 16:15 UTC, xwalls commented on MANUAL.md
> +- Tener un sistema operativos (windows, ubuntu, macOs)
me gusta pero no creo que tengamos la capacidad de estar haciendo pruebas en mac

2021-04-14 16:41 UTC, MaritzaB requested changes
Holi @xwalls  te dejo la segunda tanda de revisión ✌🏽.

2021-04-14 16:41 UTC, MaritzaB commented on MANUAL.md
> +# Manual de instalacion y ejecución
```suggestion
# Manual de instalación y ejecución
```

2021-04-14 16:41 UTC, MaritzaB commented on MANUAL.md
> +
@xwalls, esta sección para qué la tienes planeada?

2021-04-14 16:41 UTC, MaritzaB commented on MANUAL.md
> +El cual contendra tres cosas (carpeta que contiene el excel, el ejecutable, las instalaciones de java)
Se me ocurre la siguiente modificación para aclarar qué es lo que van a encontrar dentro del zip. Hasta abajo ya solo habría que sustituir por el nombre de los archivos y carpetas. ¿Qué opinas?
```suggestion
La aplicación del juego _10 nativos dijeron_ se encuentra dentro del archivo comprimido 'aplicacion.zip'.
Dentro del comprimido tenemos lo siguiente:

1. Carpeta que contiene el excel: `carpeta/archivo_de_excel.xlsx`
1. Ejecutable: `aplicación.exe`
1. Instalaciones de java: `nombre del archivo`
```

2021-04-14 16:41 UTC, MaritzaB commented on MANUAL.md
> +Para ejecutar la aplicacion debemos hacer doble click sobre el archivo `ejecutar_en_windows.bat`
¿Es en esta parte donde me comentabas que no deben de extraer el archivo?

2021-04-14 16:41 UTC, MaritzaB commented on MANUAL.md
> +Para ejecutar la aplicacion debemos hacer doble click sobre el archivo `ejecutar_en_windows.bat`
Si es así, entonces podría quedar así:
```suggestion
Para ejecutar la aplicacion debemos hacer doble click sobre el archivo `ejecutar_en_windows.bat`. Esto se debe de hacer sin descomprimir el archivo `aplicación.zip`.
```

2021-04-14 16:41 UTC, MaritzaB commented on MANUAL.md
> +- ejecutar en windows.bat
¿Dentro de la carpeta de 10 nativos están todos los archivos?
Entonces talvez podríamos específicar un poco mas.
```suggestion
Dentro de la carpeta 10 nativos se encuentran los siguientes archivos:
- `src/surveys.xlsx`
- `10-nativos-dijeron.jar`
- Instalaciones de java (instalaciones para x64 y x86)
- `windows.bat`
```
Este archivo `windows.bat` lo tienen que ejecutar? Si es así, entonces talvez deba de ir en la sección de `### Ejecución`

2021-04-15 16:38 UTC, xwalls reviewed
atiendo la revisión de maritza

2021-04-15 16:38 UTC, xwalls commented on MANUAL.md
> +
esta sección está planeada para que sepamos cómo modificar y agregar nuevas preguntas en el excel que posteriormente son cargadas en la aplicación

2021-04-15 16:38 UTC, xwalls commented on MANUAL.md
> +Para ejecutar la aplicacion debemos hacer doble click sobre el archivo `ejecutar_en_windows.bat`
al contrario!
deben de descomprimir el .zip
que te parece @MaritzaB ?

2021-04-15 16:38 UTC, xwalls commented on MANUAL.md
> +- ejecutar en windows.bat
me gusta, solo que esta sección tiene como objetivo que sepan todo lo que contiene el comprimido.
te parece bien si este se queda así?
@MaritzaB

2021-04-15 16:38 UTC, xwalls commented on MANUAL.md
> +El cual contendra tres cosas (carpeta que contiene el excel, el ejecutable, las instalaciones de java)
muchas gracias, acepto tu sugerencia!

2021-04-15 16:38 UTC, xwalls commented on MANUAL.md
> +# Manual de instalacion y ejecución
gracias!, aceptando tu sugerencia...

2021-04-15 20:36 UTC, MaritzaB commented on MANUAL.md
> +
Ahhh okok ya entiendo! Tenkius

2021-04-15 20:36 UTC, MaritzaB commented on MANUAL.md
> +Para ejecutar la aplicacion debemos hacer doble click sobre el archivo `ejecutar_en_windows.bat`
aah okok, entendí al revés jajaja 😅

2021-04-16 19:16 UTC, MaritzaB requested changes
Hola @xwalls te dejo la segunda tanda de revision.

2021-04-16 19:16 UTC, MaritzaB commented on MANUAL.md
> +### MODIFICACION DE LAS PREGUNTAS
¿Qué te parece este título ?
```suggestion
### Instrucciones para modificar las preguntas del juego de 10 nativos dijeron
```

2021-04-16 19:16 UTC, MaritzaB commented on MANUAL.md
> +- aqui se podran hacer modificaciones a las preguntas deseadas
```suggestion
1. Abrir la carpeta 'SRC'
2. Abrir el archivo de excel "survey.xlsx". Aqui se podran modificar, agregar o quitar las preguntas deseadas.
```

2021-04-16 19:16 UTC, MaritzaB commented on MANUAL.md
> +Para ejecutar la aplicacion debemos hacer doble click sobre el archivo `ejecutar_en_windows.bat`
Entonces talvez podría ser algo así:
```suggestion
Para ejecutar la aplicacion primero debemos de extraer el contenido del archivo `aplicacion.zip`.
Posteriormente, debemos hacer doble click sobre el archivo `ejecutar_en_windows.bat` 
```

2021-04-16 19:41 UTC, nepito commented on MANUAL.md
> +
> esta sección está planeada para que sepamos cómo modificar y agregar nuevas preguntas en el excel que posteriormente son cargadas en la aplicación
Tal vez, esto debería de estar en el README

2021-04-16 20:19 UTC, nepito requested changes

2021-04-16 20:19 UTC, nepito commented on MANUAL.md
> +- abrir la carpeta 'SRC'
```suggestion
Esta sección está planeada para que sepamos cómo modificar y agregar nuevas preguntas en el excel que posteriormente son cargadas en la aplicación
- abrir la carpeta 'SRC'
```

2021-04-16 20:19 UTC, nepito commented on MANUAL.md
> +2. Abrir el archivo de excel "survey.xlsx". Aqui se podran modificar, agregar o quitar las preguntas deseadas.
Cambia el estilo:
```suggestion
2. Abrir el archivo de excel "survey.xlsx". Aquí podremos modificar, agregar o quitar las preguntas deseadas.
```

2021-04-16 20:19 UTC, nepito commented on MANUAL.md
> +### Instrucciones para modificar las preguntas del juego de 10 nativos dijeron
Aquí podemos agregar la explicación que le diste a @MaritzaB :
```suggestion
### Instrucciones para modificar las preguntas del juego de 10 nativos dijeron
Esta sección está planeada para que sepamos cómo modificar y agregar nuevas preguntas en el excel que posteriormente son cargadas en la aplicación:
```

2021-04-16 20:47 UTC, xwalls commented on MANUAL.md
> +- abrir la carpeta 'SRC'
gracias nepo! acepto tu sugerencia.

2021-04-16 20:48 UTC, xwalls commented on MANUAL.md
> +2. Abrir el archivo de excel "survey.xlsx". Aqui se podran modificar, agregar o quitar las preguntas deseadas.
gracias nepo! tenía esa mala costumbre

2021-04-16 20:48 UTC, xwalls commented on MANUAL.md
> +### Instrucciones para modificar las preguntas del juego de 10 nativos dijeron
gracias nepo! acepto tu sugerencia.

2021-04-16 21:03 UTC, MaritzaB requested changes
Listo @xwalls  ya dejé otros comentarios

2021-04-16 21:03 UTC, MaritzaB commented on MANUAL.md
> +1. Instalaciones de java: `nombre del archivo`
Creo que esta línea ya se encuentra abajo en la 23, donde dice Isntalacioness de java (para x64 y x86). Yo sugiero eliminarla.
```suggestion
```

2021-04-16 21:03 UTC, MaritzaB commented on MANUAL.md
> +_Qué cosas necesitas tener antes de poder ejecutar la aplicación:_
Pareciera que esta línea es una pregunta pero no tiene los signos de interrogación. ¿Qué te parece si la cambiamos por lo siguiente?
```suggestion
_Cosas que necesitas tener antes de poder ejecutar la aplicación:_
```

2021-04-19 17:25 UTC, xwalls commented on MANUAL.md
> +1. Instalaciones de java: `nombre del archivo`
gracias maritza, veo bien tu sugerencia!

2021-04-19 17:25 UTC, xwalls commented on MANUAL.md
> +_Qué cosas necesitas tener antes de poder ejecutar la aplicación:_
completamente maritza, agregando!

2021-04-19 18:05 UTC, MaritzaB requested changes
Ya quedó @xwalls , te dejo otros pocos comentarios 🤪

2021-04-19 18:05 UTC, MaritzaB commented on MANUAL.md
> +_Este es el manual de instalación del juego _10 nativos dijeron_. Aquí veremos los pre-requisitos de sistema para poder instalar y ejecutar esta aplicacion, así como las instrucciones para hacerlo._
Creo que nos conviene utilizar _itálicas_ solo para resaltar ciertas palabras y no en toda una oración, tu que opinas @xwalls ?
```suggestion
Este es el manual de instalación del juego _10 nativos dijeron_. Aquí veremos los pre-requisitos de sistema para poder instalar y ejecutar esta aplicacion, así como las instrucciones para hacerlo.
```

2021-04-19 18:05 UTC, MaritzaB commented on MANUAL.md
> +_Cosas que necesitas tener antes de poder ejecutar la aplicación:_
```suggestion
Cosas que necesitas tener antes de poder ejecutar la aplicación:
```

2021-04-19 18:05 UTC, MaritzaB commented on MANUAL.md
> +2. Abrir el archivo de excel "survey.xlsx". Aquí podremos modificar, agregar o quitar las preguntas deseadas.
```suggestion
2. Abrir el archivo de excel `survey.xlsx`. Aquí podremos modificar, agregar o quitar las preguntas deseadas.
```

2021-04-19 18:05 UTC, MaritzaB commented on MANUAL.md
> +con ❤️ por el equipo de Ciencia de Datos de GECI 😊
```suggestion
Con ❤️, el equipo de Ciencia de Datos de GECI 😊
```

2021-04-19 18:36 UTC, xwalls commented on MANUAL.md
> +_Este es el manual de instalación del juego _10 nativos dijeron_. Aquí veremos los pre-requisitos de sistema para poder instalar y ejecutar esta aplicacion, así como las instrucciones para hacerlo._
es un buen detalle, agregando!

2021-04-19 18:36 UTC, xwalls commented on MANUAL.md
> +_Cosas que necesitas tener antes de poder ejecutar la aplicación:_
es un buen detalle, agregando!

2021-04-19 18:36 UTC, xwalls commented on MANUAL.md
> +2. Abrir el archivo de excel "survey.xlsx". Aquí podremos modificar, agregar o quitar las preguntas deseadas.
es un buen detalle, agregando...!

2021-04-19 18:37 UTC, xwalls commented on MANUAL.md
> +con ❤️ por el equipo de Ciencia de Datos de GECI 😊
vaya que le pusiste amor a estas revisiones, agregando muchas gracias!

2021-04-20 15:48 UTC, marthapaolajm commented
Hola @xwalls ! Te dejo los comentarios de los pasos que se me dificultaron 😁

2021-04-20 18:49 UTC, marthapaolajm requested changes
Hola @xwalls aqui te dejo mis comentarios, espero que te sean útiles 🤗

2021-04-20 18:49 UTC, marthapaolajm commented on MANUAL.md
> +- [Tener java Jre8 Instalado](https://www.oracle.com/mx/java/technologies/javase-jre8-downloads.html)
Aqui, seria mejor que cambiemos el link por el de los archivos de drive, señalando como se llama el archivo que debemos descargar. Ya que ver el link de la página y tener los archivos de drive, puede llegar a ser confuso de donde descargarlo 😀

2021-04-20 18:49 UTC, marthapaolajm commented on MANUAL.md
> +La aplicación del juego _10 nativos dijeron_ se encuentra dentro del archivo comprimido 'aplicacion.zip'.
En esta parte, es importante señalar dónde se encuentra la "aplicacion.zip", ya que no se entiende bien dónde está. También debemos actualizar su nombre, porque tengo entendido que ahora es el archivo de "aplicación con  ejecutable.zip" de los archivos de drive 🔎

2021-04-20 18:49 UTC, marthapaolajm commented on MANUAL.md
> +Dentro del comprimido tenemos lo siguiente:
Podríamos cambiar "comprimido", por el nombre del archivo, para que sea más claro 🤔

2021-04-20 18:49 UTC, marthapaolajm commented on MANUAL.md
> +1. Carpeta que contiene el excel: `carpeta/archivo_de_excel.xlsx`
Este paso no es muy claro, creo que deberíamos poner el nombre de la carpeta y del archivo que aparecen realmente 🤔

2021-04-20 18:49 UTC, marthapaolajm commented on MANUAL.md
> +1. Ejecutable: `aplicación.exe`
No es claro donde se encuentra, debemos describirlo más 🤓

2021-04-20 18:49 UTC, marthapaolajm commented on MANUAL.md
> +Dentro de la carpeta 10 nativos se encuentran los siguientes archivos:
En esta parte, debemos añadir la opción de cuando no te deja abrir este archivo, que fue mi caso:
![imagen](https://user-images.githubusercontent.com/77699134/115447042-e1e1bd00-a1cc-11eb-8633-6603e6c673d3.png)
![imagen](https://user-images.githubusercontent.com/77699134/115447091-f02fd900-a1cc-11eb-95d8-cd8ca52509ec.png)
Y a pesar de que permite los accesos, no se logró ejecutar nada 😟

2021-04-21 19:16 UTC, xwalls commented on MANUAL.md
> +- [Tener java Jre8 Instalado](https://www.oracle.com/mx/java/technologies/javase-jre8-downloads.html)
hola martha!
gracias me encargare de agregar esos links

2021-04-21 19:17 UTC, xwalls commented on MANUAL.md
> +La aplicación del juego _10 nativos dijeron_ se encuentra dentro del archivo comprimido 'aplicacion.zip'.
excelente observación, hare la modificación. Gracias!

2021-04-21 19:19 UTC, xwalls commented on MANUAL.md
> +Dentro del comprimido tenemos lo siguiente:
acepto tu sugerencia! ;)

2021-04-21 19:44 UTC, xwalls commented on MANUAL.md
> +1. Carpeta que contiene el excel: `carpeta/archivo_de_excel.xlsx`
me pongo manos a la obra! gracias!

2021-04-21 19:44 UTC, xwalls commented on MANUAL.md
> +1. Ejecutable: `aplicación.exe`
estoy en ello ;)

2021-04-21 19:49 UTC, xwalls commented on MANUAL.md
> +Dentro de la carpeta 10 nativos se encuentran los siguientes archivos:
El problema de la primera imagen ocurre debido a que estamos tratando de ejecutar la aplicación desde dentro del archivo comprimido.
Pero debido a que ese paso 'Descomprimir el archivo .zip' no se encuentra en el manual, es natural que haya sucedido.
Agregare ese paso en el manual ;)


Lo que sucede en la segunda imagen es que en windows. Como usuario se nos pide validar de manera manual, el tener que darle acceso a una aplicación que está a punto de ejecutarse por primera vez.
Esto solo ocurre y ocurrirá la primera vez que se ejecute la aplicación.
Esto aun no esta en el manual pero es una excelente idea agregarlo para atar todos los cabos sueltos. muchas gracias!

2021-04-22 19:21 UTC, marthapaolajm requested changes
Hola @xwalls aqui te dejo mis nuevos comentarios jaja, espero que te sean de ayuda 😜

2021-04-22 19:21 UTC, marthapaolajm commented on MANUAL.md
> +- [Descargar el comprimido de la aplicación](https://drive.google.com/file/d/1pX3LwA_AV7ky7LiQpopkfBTTpyd835K6/view?usp=sharing)
En el punto de "Descargar el comprimido de la aplicación", podemos modificarlo como ""Descargar el comprimido de la aplicación llamado 'nombre la carpeta' ", para que las personas que lo ejecuten no se confundan en nada y sea todo más claro 😁

2021-04-22 19:21 UTC, marthapaolajm commented on MANUAL.md
> +El cual debe de ser descomprimido sin importar su ubicacion.
Aquí cuando decimos "La aplicación del juego _10 nativos dijeron se encuentra dentro del archivo comprimido llamado `aplicacion con ejecutable.zip`.El cual debe de ser descomprimido sin importar su ubicación.", podríamos reemplazarlo para primero explicar cómo descomprimir el archivo; explicándolo con pasos, para que no haya confusión. Adjunto las capturas de pantalla que podrían servir en la explicación 🤗

![imagen](https://user-images.githubusercontent.com/77699134/115767973-8d6e4700-a35e-11eb-99e6-aa7dcb97765f.png)
![imagen](https://user-images.githubusercontent.com/77699134/115767987-9232fb00-a35e-11eb-9695-b9e794962136.png)
![imagen](https://user-images.githubusercontent.com/77699134/115768003-965f1880-a35e-11eb-88b7-0b4f1cff6b7a.png)

2021-04-22 19:21 UTC, marthapaolajm commented on MANUAL.md
> +El cual debe de ser descomprimido sin importar su ubicacion.
```suggestion
El cual debe de ser descomprimido sin importar su ubicación.
```

2021-04-22 19:21 UTC, marthapaolajm commented on MANUAL.md
> +Una vez descomprimido se optendra una carpeta llamada `10 nativos dijeron`.
Debemos cambiar el nombre de la carpeta que se obtiene, porque sale una con el mismo nombre del archivo descomprimido y la de '10 nativos dijeron' está dentro de esa, no es la que sale primero. Y podemos aclarar que la carpeta que sale al ser descomprimido el archivo es una que sale sin el ziper visualmente. Adjunto capturas de pantalla para que sea más clara la explicación 😬
![imagen](https://user-images.githubusercontent.com/77699134/115768888-bfcc7400-a35f-11eb-8903-ec088b46b58a.png)
![imagen](https://user-images.githubusercontent.com/77699134/115768902-c65aeb80-a35f-11eb-853c-15fb51f936a7.png)

2021-04-22 19:21 UTC, marthapaolajm commented on MANUAL.md
> +- `verificador.bat`
Se podría agregar la captura de pantalla de como se ven visualmente para que se familiaricen rápido 🕺
![imagen](https://user-images.githubusercontent.com/77699134/115769313-41240680-a360-11eb-8c55-4bd9b27046da.png)
![imagen](https://user-images.githubusercontent.com/77699134/115769393-5ac54e00-a360-11eb-8d42-c153dbee6a37.png)

2021-04-22 19:21 UTC, marthapaolajm commented on MANUAL.md
> +Posteriormente, debemos entrar en esta carpeta `10 nativos dijeron` y dependiendo de nuestro sistema operativo haremos lo siguiente:
Debemos aclarar que la carpeta '10 nativos dijeron' no es la obtenida, la obtenida en 'aplicación con ejecutable' y la de '10 nativos dijeron' está adentro 😺

2021-04-22 19:21 UTC, marthapaolajm commented on MANUAL.md
> +- Dentro de la carpeta `10 nativos dijeron`
Tal vez podríamos añadir antes de ese paso el abrir la carpeta descomprimida 'aplicación con ejecutable' 🤔

2021-04-22 19:21 UTC, marthapaolajm commented on MANUAL.md
> +- Despues aparecera una ventana emergente pidiendo acceso para la aplicación java. Donde debemos hacer click en `'Permitir Acceso'`
En esta parte, esta ves que lo corrí me salio antes de esa ventana emergente todo eso, podríamos considerar agregarlo por si a alguien mas le sale y que no se asuste 😜, agrego las capturas:
![imagen](https://user-images.githubusercontent.com/77699134/115770597-c2c86400-a361-11eb-90c0-2bd2e780bee0.png)
![imagen](https://user-images.githubusercontent.com/77699134/115770616-c825ae80-a361-11eb-8fd7-0764e2a7042d.png)
![imagen](https://user-images.githubusercontent.com/77699134/115770668-d7a4f780-a361-11eb-8a27-820beaad7c1a.png)
![imagen](https://user-images.githubusercontent.com/77699134/115770693-e095c900-a361-11eb-8a9f-88457d601d38.png)
![imagen](https://user-images.githubusercontent.com/77699134/115770712-e4295000-a361-11eb-9570-a114e06369eb.png)

2021-04-22 19:21 UTC, marthapaolajm commented on MANUAL.md
> +Para finalizar, despues de una ejecución se nos abrira automaticamente el navegador con una pagina en concreto:
En mi caso, cuando ejecuté la terminal parecía que ya se había ejecutado y no se había abierto nada, entonces la cerré. Y cuando intente meter a la página manualmente me aparece error (metiendolo en el navegador que estaba utilizando en el momento no el predeterminado). Podríamos aclarar que puede ocurrir esto y que chequen bien su navegador determinado y si no, lo vuelvan a ejecutar (en mi caso estuvo abierto en mi navegador predeterminado y cuando intente abrirlo en el navegador que estaba usando me salia error) Pero sin darme cuenta aun de esto, lo volvi a ejecutar y ya se abrió automáticamente el navegador predeterminado, ejecutando correctamente.
Espero haber sido clara, cualquier duda de este suceso, podemos hacer tomate o me puedes preguntar 😁
![imagen](https://user-images.githubusercontent.com/77699134/115771724-2606c600-a363-11eb-8449-6bbec003f25f.png)
Podríamos añadir como debe aparecer la página al ejecutarse y la terminal para que no haya sustos 🤪:
![imagen](https://user-images.githubusercontent.com/77699134/115772202-afb69380-a363-11eb-8b5b-47cc06e9483a.png)

![imagen](https://user-images.githubusercontent.com/77699134/115771991-73833300-a363-11eb-8d22-a78e874ac6ef.png)

2021-04-22 19:21 UTC, marthapaolajm commented on MANUAL.md
> +2. Abrir el archivo de excel `survey.xlsx`. Aquí podremos modificar, agregar o quitar las preguntas deseadas.
En esta parte se podría añadir las capturas de pantalla de cada paso para que sea todo más visual, pero tampoco es indispensable, así se entiende muy bien. Tal ves solo señalar en qué carpeta seguimos trabajando por cualquier cosa y al final decir que se tienen que guardar los cambios o si se debe hacer otra cosa antes de guardar para que se queden los cambios señalarla🤗
![imagen](https://user-images.githubusercontent.com/77699134/115772963-9235f980-a364-11eb-8aa8-019a03aaa31a.png)
![imagen](https://user-images.githubusercontent.com/77699134/115772978-96621700-a364-11eb-9d61-5fc5baa9ea47.png)

En esta captura tal ves seria bueno hacer otra hoja que nomas diga "pregunta, pregunta, pregunta", para tomarle captura como muestra y no mostrar la de las preguntas ya jaja
![imagen](https://user-images.githubusercontent.com/77699134/115772988-9bbf6180-a364-11eb-8162-232af8bbc517.png)
![imagen](https://user-images.githubusercontent.com/77699134/115773116-c6a9b580-a364-11eb-8664-6c8d36e13a8c.png)

2021-04-23 16:58 UTC, xwalls commented on MANUAL.md
> +- [Descargar el comprimido de la aplicación](https://drive.google.com/file/d/1pX3LwA_AV7ky7LiQpopkfBTTpyd835K6/view?usp=sharing)
me gusta!
agregando...

2021-04-23 17:19 UTC, xwalls commented on MANUAL.md
> +El cual debe de ser descomprimido sin importar su ubicacion.
gracias por las imágenes! agregando..

2021-04-23 17:20 UTC, xwalls commented on MANUAL.md
> +El cual debe de ser descomprimido sin importar su ubicacion.
gracias! eliminare esta línea para detallar el proceso de extracción ;)

2021-04-23 17:22 UTC, xwalls commented on MANUAL.md
> +Una vez descomprimido se optendra una carpeta llamada `10 nativos dijeron`.
muchas gracias martha!
ahora con el nuevo comprimido, al extraerlo únicamente obtendremos una carpeta '10 nativos dijeron' con los archivos dentro. creo que sera mas facil y comodo ;)

2021-04-23 17:23 UTC, xwalls commented on MANUAL.md
> +- `verificador.bat`
@marthapaolajm 
perfecto! te parece bien si entonces borro el texto para dejar solamente la imagen?

2021-04-23 17:24 UTC, xwalls commented on MANUAL.md
> +Posteriormente, debemos entrar en esta carpeta `10 nativos dijeron` y dependiendo de nuestro sistema operativo haremos lo siguiente:
con el nuevo comprimido si sera asi ;)
la carpeta '10 nativos dijeron' será la obtenida

2021-04-23 17:24 UTC, xwalls commented on MANUAL.md
> +- Dentro de la carpeta `10 nativos dijeron`
con el nuevo comprimido si sera asi ;)
la carpeta '10 nativos dijeron' será la obtenida

2021-04-23 17:25 UTC, xwalls commented on MANUAL.md
> +- Despues aparecera una ventana emergente pidiendo acceso para la aplicación java. Donde debemos hacer click en `'Permitir Acceso'`
excelente idea! agregando...

2021-04-23 17:38 UTC, xwalls commented on MANUAL.md
> +Para finalizar, despues de una ejecución se nos abrira automaticamente el navegador con una pagina en concreto:
muchas gracias! agregare las capturas y si el problema que mencionaste primero persiste en la siguiente revision, tenemos el tomate va?

2021-04-23 17:43 UTC, xwalls commented on MANUAL.md
> +2. Abrir el archivo de excel `survey.xlsx`. Aquí podremos modificar, agregar o quitar las preguntas deseadas.
Hola marta, para no abusar tanto de las imágenes, optare solo por una imagen a ver qué te parece el resultado ;)
gracias!

2021-04-23 17:47 UTC, xwalls commented on MANUAL.md
> +- `verificador.bat`
lo deje a ver que tal te parece

2021-04-26 21:19 UTC, marthapaolajm requested changes
Hola @xwalls, felicidades por este manual, 🎊 🎈 esta vez que lo volví a ejecutar no tuve ninguna duda ni inquietud. Sin embargo, te dejo algunos comentarios que creo que a las personas que lo ejecuten por primera vez les podría ayudar a tener más detalladas. Cualquier duda podemos hacer un tomate!😁🎆

2021-04-26 21:19 UTC, marthapaolajm commented on MANUAL.md
> +- [Tener java Jre8 instalado](https://drive.google.com/file/d/1fsPZxkXY4lly9LJyNBw0ZrnrhmdTVgRX/view?usp=sharing)
Podríamos cambiar la descripción de la liga de "Tener java Jre8" a "Tener java Jre8, descargando el comprimido "instalaciones de java.zip"", para que sepan que desacrgando dicha carpeta ya estará la instalación y no piensen que deben hacer algo más 😃

2021-04-26 21:19 UTC, marthapaolajm commented on MANUAL.md
> +![image](https://user-images.githubusercontent.com/9456708/115905916-aab51b00-a41b-11eb-8807-9aa49dc77d34.png)
En esta sección, me encanto que cambiaras el nombre de la carpeta para que como mencionaste, no este una carpeta dentro de otra. Entonces si gustan hay que cambiar las fotos, de tal forma que ahora salga como carpeta principal la de 10 nativos dijeron, porque ahorita sale la anterior. Te adjunto las capturas acordes 🤗
![imagen](https://user-images.githubusercontent.com/77699134/116148553-e3f8bf80-a695-11eb-85d7-48940011ca1b.png)
![imagen](https://user-images.githubusercontent.com/77699134/116148578-ebb86400-a695-11eb-9b1c-5bc97ad546cf.png)
![imagen](https://user-images.githubusercontent.com/77699134/116148606-f246db80-a695-11eb-80a9-e888bd0c7de9.png)

2021-04-26 21:19 UTC, marthapaolajm commented on MANUAL.md
> +![image](https://user-images.githubusercontent.com/9456708/115907538-dfc26d00-a41d-11eb-85d5-decc9257fd22.png)
Igual aquí, hay que cambiar la imagen para que en donde salen las ubicaciones anteriores en los archivos, salga directamente la de 10 nativos dijeron, y no haya confusiones 😁
![imagen](https://user-images.githubusercontent.com/77699134/116148802-3934d100-a696-11eb-9046-8ab86807bea2.png)

2021-04-26 21:19 UTC, marthapaolajm commented on MANUAL.md
> +1. Abrir la carpeta 'SRC'
En esta parte podríamos señalar antes o en este paso que estamos en la carpeta descomprimida, porque en ambas salen los mismos archivos y podría haber confusión. O si puede ser en cualquiera de las dos, señalarlo 😜

2021-04-26 21:19 UTC, marthapaolajm commented on MANUAL.md
> +Para finalizar, despues de una ejecución se nos abrira automaticamente el navegador con una pagina en concreto:
Perfecto!

2021-04-26 21:19 UTC, marthapaolajm commented on MANUAL.md
> +Para finalizar, despues de una ejecución se nos abrira automaticamente el navegador con una pagina en concreto:
Creo que sería bueno, señalar que se abrirá en el navegador predeterminado 🤓

2021-04-26 21:19 UTC, marthapaolajm commented on MANUAL.md
> +__NOTA__: Si la pagina no aparece automaticamente, podemos ir a la direccion anterior de manera manual, donde podremos ver nuestra aplicacion ejecutandose. De lo contrario algun problema debio haber
En esta parte también hay que señalar que se debe abrir manualmente en el navegador predeterminado, ya que si no es así. No se lograra ejecutar y aparecerá error en la página 🤗

2021-04-27 18:54 UTC, MaritzaB commented on MANUAL.md
> +__NOTA__: Si la pagina no aparece automaticamente, podemos ir a la direccion anterior de manera manual, donde podremos ver nuestra aplicacion ejecutandose. De lo contrario algun problema debio haber
¿Eso quiere decir que se puede ejecutar el cualquier navegador siempre y cuando sea el predeterminado? 🤔

2021-04-27 18:55 UTC, MaritzaB commented on MANUAL.md
> +Para finalizar, despues de una ejecución se nos abrira automaticamente el navegador con una pagina en concreto:
¿El navegador predeterminado dependiendo de la configuración de nuestra computadora?

2021-04-27 19:24 UTC, MaritzaB commented on MANUAL.md
> +Para finalizar, despues de una ejecución se nos abrira automaticamente el navegador con una pagina en concreto:
Ya platicamos @xwalls y yo con respecto a esta sugerencia. Ya que se puede usar cualquier navegador parece que no es necesario mencionar lo del navegador predeterminado 😁, pero muy buena observación.

2021-04-27 19:24 UTC, MaritzaB commented on MANUAL.md
> +__NOTA__: Si la pagina no aparece automaticamente, podemos ir a la direccion anterior de manera manual, donde podremos ver nuestra aplicacion ejecutandose. De lo contrario algun problema debio haber
En esta parte es lo mismo que la anterior.

2021-04-27 20:28 UTC, MaritzaB commented on MANUAL.md
> +![image](https://user-images.githubusercontent.com/9456708/115905916-aab51b00-a41b-11eb-8807-9aa49dc77d34.png)
Listo @marthapaolajm , ya están actualizadas las imágenes 🙌🏽 . Muchas gracias :)

2021-04-27 20:29 UTC, MaritzaB commented on MANUAL.md
> +1. Abrir la carpeta 'SRC'
Listo!

2021-04-27 21:33 UTC, MaritzaB approved these changes

2021-04-27 21:34 UTC, merged