Crea readme.md
IslasGECI/juego_10_nativos_dijeron pull request #8
Opened 2019-08-15 19:08 UTC by fiorellam

2019-08-17 03:24 UTC, devarops requested changes
Por favor despelusa el README usando un _linter_ para Markdown. Yo uso [markdownlint](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint).

2019-08-22 05:38 UTC, devarops requested changes
A veces hablas "de usted": _seleccione_, _ejecute_, _abra_; pero al final hablas "de tú": _escribe_.

Por favor usa una sóla forma. Yo prefiero  _selecciona_, _ejecuta_, _abre_ ya que así nos hablamos entre nosotros, sin embargo, tú puedes elegir la forma que prefieras, pero sólo una.

2019-08-22 05:38 UTC, evaristor commented
A veces hablas "de usted": _seleccione_, _ejecute_, _abra_; pero al final hablas "de tú": _escribe_.

Por favor usa una sóla forma. Yo prefiero  _selecciona_, _ejecuta_, _abre_ ya que así nos hablamos entre nosotros, sin embargo, tú puedes elegir la forma que prefieras, pero sólo una.

2019-08-22 13:42 UTC, devarops requested changes
En varios casos usas sólo minúsculas cuando en los mensajes aparece la primer letra en mayúscula. Por ejemplo _intelliJ_ debería ser _IntelliJ_, , _new project..._ debería ser _New Project..._,  _new_ debería ser _New..._

2019-08-22 13:42 UTC, evaristor commented on README.md
> +
Parece que los 4 pasos anteriores quedan anulados con los siguientes pasos. Nota que pones "Abra IntelliJ" dos veces. ¿Les fata un subtítulo a los cuatro pasos anteriores y otro subtítulo a los siguientes pasos?

2019-08-22 13:42 UTC, evaristor commented on README.md
> +* Cuando el proyecto se haya abierto, agregue en la carpeta **src** el archivo "Juego.xlsx".
¿Dónde puedo encontrar `Juego.xlsx`?

2019-08-22 13:42 UTC, evaristor commented on README.md
> +* Seleccione una opción en **project sdk**, en caso de que no aparezca ninguna opción, da click en **new** y especifique la ruta en la que se encuentra el directorio del jdk de Java.
Creo que le falta un punto para separar en dos oraciones:
> Seleccione una opción en **project sdk**. En caso de que no aparezca ninguna opción, da click en **new** y especifique la ruta en la que se encuentra el directorio del jdk de Java.

2019-08-22 15:25 UTC, evaristor commented
Los guiones bajos (pisos) se ven raros en el título.

2019-08-23 16:09 UTC, devarops requested changes
Por favor incluye una sunsección de instalación para Linux (ya que es el S.O. que usa el equipo). El comando para instalación en Ubunt es:
`sudo apt install default-jdk`

2019-08-23 20:20 UTC, devarops requested changes

2019-08-23 20:20 UTC, evaristor commented on README.md
> +
Ya lo volví a hacer todo. Me parece que los primeros cuatro pasos sobran.

2019-08-27 19:24 UTC, devarops requested changes

2019-08-27 19:24 UTC, devarops commented on README.md
> +* Da click en el botón que tiene un recuadro rojo.
¿Qué comando representa ese ícono? En mi IDE no me aparece exactamente en el mismo lugar y hay dos íconos similares pero que ejecutan comandos distintos: uno es _Reimport all Maven Projects_ y el otro es _Syncronize_.
No sé a cual de los dos le debo picar

2019-08-27 19:24 UTC, devarops commented on README.md
> +* Da click en correr proyecto o en el botón con recuadro rojo que se puede encontrar en el archivo Main.java
No encuentro esto. Ni el botón ni el archivo `Main.java`

2019-08-27 19:32 UTC, fiorellam commented on README.md
> +* Da click en el botón que tiene un recuadro rojo.
Sería el de _Reimport all Maven Projects_

2019-08-27 19:41 UTC, fiorellam commented on README.md
> +* Da click en correr proyecto o en el botón con recuadro rojo que se puede encontrar en el archivo Main.java
Ok, me parece que se debe a que IntelliJ en ocasiones no reconoce la carpeta _src_ como la carpeta raíz, por lo que se debe hacer esto:
Se da click derecho a la carpeta _src_
![image](https://user-images.githubusercontent.com/24512323/63802400-67617c80-c8c7-11e9-8a48-b9194e2505db.png)

El archivo Main.java se encuentra aquí src/mx/org/islas/Main.java
![image](https://user-images.githubusercontent.com/24512323/63802510-a98abe00-c8c7-11e9-9030-2d085a645aa7.png)

2019-08-27 19:49 UTC, devarops requested changes

2019-08-27 19:49 UTC, devarops commented on README.md
> +* Da click en el botón que tiene un recuadro rojo.
Entonces hay que explicar esto en el `README`, no?

2019-08-27 19:49 UTC, devarops commented on README.md
> +* Da click en correr proyecto o en el botón con recuadro rojo que se puede encontrar en el archivo Main.java
Entonces hay que explicar esto en el `README`, no?

2019-08-30 00:36 UTC, devarops approved these changes

2019-09-03 18:59 UTC, merged